mdc check for resolve-deps. Stop run-tests.sh if mdc fails.
It's easy to forget `npm install` for a clean conlink checkout.  With
this change, mdc now fails if resolve-deps isn't found and prompts the
user with a possible resolution.

run-test.sh should also stop running tests if mdc fails.

diff --git a/mdc b/mdc
--- a/mdc
+++ b/mdc
@@ -17,6 +17,7 @@ LS=$(which ls)
 RESOLVE_DEPS="${RESOLVE_DEPS-./node_modules/@lonocloud/resolve-deps/resolve-deps.py}"
 DOCKER_COMPOSE="${DOCKER_COMPOSE:-docker-compose}"
 
+[ -f "${RESOLVE_DEPS}" ] || die "Missing ${RESOLVE_DEPS}. Perhaps 'npm install'?"
 MODE_SPEC="${1}"; shift
 if [ "${RESOLVE_DEPS}" ]; then
     MODES="$(${RESOLVE_DEPS} "${MODES_DIR}" ${MODE_SPEC})"
